# Generated by Django 5.2.5 on 2025-09-25 02:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10),
        ),
    ]
