# Generated by Django 5.2.5 on 2025-09-24 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_emailmessage_support_code_and_more'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='wallet.cart'),
        ),
    ]
