# Generated by Django 5.2.5 on 2025-09-24 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
        ('reservation', '0005_visit_status_alter_timesheet_visit_time_visitlog_and_more'),
        ('user_account', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('doctor', 'clinic', 'date', 'start_meet'), name='unique_visit_per_slot'),
        ),
    ]
