# Generated by Django 5.2.5 on 2025-09-24 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
        ('reservation', '0006_visit_unique_visit_per_slot'),
        ('user_account', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='visit',
            name='unique_visit_per_slot',
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'completed')), fields=('doctor', 'clinic', 'date', 'start_meet'), name='unique_visit_per_completed_slot'),
        ),
    ]
