services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - "8000"
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
