version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file: .env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    env_file: .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
