# Base Python image
FROM python:3.11-slim

# set work directory
WORKDIR /usr/src/app

# Avoids Python writing pyc files 
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy project code
COPY . .

# Runs Django dev server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

