# Generated by Django 5.2.5 on 2025-09-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinic_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='clinic_phone',
        ),
        migrations.AddField(
            model_name='doctor',
            name='contract_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='contract_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='university',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
