# Generated by Django 5.2.5 on 2025-09-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_doctor_clinic_name_remove_doctor_clinic_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('GP', 'General Practice'), ('CARD', 'Cardiology'), ('DERM', 'Dermatology'), ('ENDO', 'Endocrinology'), ('NEUR', 'Neurology'), ('ORTH', 'Orthopedics'), ('PED', 'Pediatrics'), ('PSY', 'Psychiatry'), ('RAD', 'Radiology'), ('OTHER', 'Other')], max_length=5, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='account.specialty'),
        ),
    ]
