# Generated by Django 5.2.5 on 2025-09-16 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with 09 (e.g., 09123456789) or +98 (e.g., +989123456789).', regex='^(?:\\+98|0)?9\\d{9}$')]),
        ),
    ]
