# Generated by Django 5.2.5 on 2025-09-25 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicdoctor',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_links', to='user_account.doctor'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='doctors',
            field=models.ManyToManyField(related_name='clinics', through='doctor.ClinicDoctor', to='user_account.doctor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='clinic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to='doctor.clinic'),
        ),
        migrations.AddField(
            model_name='comment',
            name='doctor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to='user_account.doctor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user_account.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicdoctor',
            unique_together={('clinic', 'doctor')},
        ),
    ]
