# Generated by Django 5.2.5 on 2025-09-21 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='working_hours',
        ),
        migrations.CreateModel(
            name='ClinicOpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')])),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='doctor.clinic')),
            ],
            options={
                'ordering': ['clinic', 'weekday', 'start'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='end_after_start')],
                'unique_together': {('clinic', 'weekday', 'start', 'end')},
            },
        ),
    ]
