# Generated by Django 5.2.5 on 2025-09-21 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0012_city_translations_country_translations_and_more'),
        ('doctor', '0003_remove_clinic_working_hours_clinicopeninghour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='cities_light.region'),
        ),
    ]
