# Generated by Django 5.2.5 on 2025-09-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_clinic_options_clinicdoctor_clinic_doctors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='doctors',
        ),
        migrations.DeleteModel(
            name='ClinicDoctor',
        ),
    ]
