# Generated by Django 5.2.5 on 2025-09-25 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_remove_clinic_doctors_delete_clinicdoctor'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_doctors', to='doctor.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_links', to='user_account.doctor')),
            ],
            options={
                'db_table': 'clinic_doctors',
                'unique_together': {('clinic', 'doctor')},
            },
        ),
        migrations.AddField(
            model_name='clinic',
            name='doctors',
            field=models.ManyToManyField(related_name='clinics', through='doctor.ClinicDoctor', to='user_account.doctor'),
        ),
    ]
